# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

reportStatus: true
updateBranch: true
deleteBranchAfterMerge: true
mergeMethod: squash

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingLabels:
  - DO NOT MERGE
  - WIP
  - blocked

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
rules:
  - minApprovals:
      MEMBER: 3
  - requiredLabels:
      - merge
