apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webapp
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: java-patterns
    app.kubernetes.io/version: '0.0.0'
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: documentation
    app.kubernetes.io/managed-by: tilt

spec:
  replicas: 1
  minReadySeconds: 60
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
        - key: 'CriticalAddonsOnly'
          operator: 'Exists'
      containers:
        - name: backend
          image: java-patterns
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 32Mi
      #          livenessProbe:
      #            httpGet:
      #              host: localhost
      #              path: /
      #              port: 8000
      #              scheme: HTTP
      #            initialDelaySeconds: 60
      #            timeoutSeconds: 5
      #            successThreshold: 1
      #            failureThreshold: 5
      #          readinessProbe:
      #            httpGet:
      #              host: localhost
      #              path: /
      #              port: 8000
      #              scheme: HTTP
      dnsPolicy: Default
#          volumeMounts:
#            - mountPath: /usr/src/app
#              name: appvolume
#            - mountPath: /usr/src/data
#              name: data
#      volumes:
#        - name: appvolume
#          emptyDir: { }
#        - name: data
#          emptyDir: { }
