github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true

image:
  file: .gitpod.Dockerfile

ports:
- port: 8000
  onOpen: open-preview

tasks:
- init: npm install && npm run all
  command: >
    npm run lerna:dist &&
    printf "\nWelcome to Java Design Patterns Docs\nTo rebuild the app, simply run './scripts/build-docs.sh' and reload index.html.\n\n" &&
    ./scripts/build-docs.sh 2>/dev/null
