pull_request_rules:
  - name: "approve automated PRs that have passed checks"
    conditions:
      - "#files<=6"
      - "base=master"
    actions:
      review:
        type: "APPROVE"
        message: "We've automatically approved this PR because the checks from the automated Pull Request have passed."
      label:
        add:
          - "auto-approved"

  - name: automatic merge on CI success require review
    conditions:
      - status-success=Travis CI - Pull Request
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
      - '#commented-reviews-by=0'
      - label!=block-merge
    actions:
      label:
        add:
          - quotes
      merge:
        method: squash
        strict: smart
        strict_method: merge

  # if there is a conflict in a backport PR, ping the author to send a proper backport PR
  - name: ping author on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message:
          This pull request has merge conflicts that must be resolved before it
          can be merged. @{{author}} please rebase it.
          https://rook.io/docs/rook/master/development-flow.html#updating-your-fork

  # automerge on master only under certain strict conditions
  - name:
      automerge merge master with specific label and approvals with code change
    conditions:
      - author=mergify[bot]
      - base=master
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
      - label!=do-not-merge
      - label=ready-to-merge
    actions:
      merge:
        method: merge
        strict: false
      dismiss_reviews: { }
      delete_head_branch: { }

  - name: automatic merge on CI success for TemplateControl
    conditions:
      - status-success=Travis CI - Pull Request
      - label=merge-when-green
      - label!=block-merge
    actions:
      merge:
        method: squash
        strict: smart

  - name: delete branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: { }

  - name: Automatically approve Dependabot PRs
    conditions:
      - base=master
      - author~=^dependabot(|-preview)\[bot\]$
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE

  - name: "delete the head branch after merge"
    conditions:
      - "merged"
    actions:
      delete_head_branch: { }

  - name: "ask to resolve conflict"
    conditions:
      - "conflict"
    actions:
      comment:
        message: "This pull request now has conflicts. Could you fix it @{{author}}? 🙏"

  - name: "remove outdated reviews"
    conditions:
      - "base=master"
    actions:
      dismiss_reviews:
        changes_requested: true
        approved: true
        message: "This Pull Request has been updated, so we're dismissing all reviews."
