# validate this file:
#   curl --data-binary @.codecov.yml https://codecov.io/validate

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: '70.0 - 100.0'
  status:
    changes: false
    project:
      default:
        informational: true
        threshold: 1%
        if_not_found: success # no commit found? still set a success
    patch:
      default:
        informational: true
        if_not_found: success

parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: false

ignore:
  - '**/*.md'
