# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Site specific data
site_name: Java Patterns
site_description: >-
  java code patterns and basic architecture designing concepts
site_author: Alexander Rogalskiy

# Canonical URL (HTML content instructs search engines that this is where the preferred version of the docs is located, useful when we have duplicate content like versioned docs)
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Choosing_between_www_and_non-www_URLs#using_%3Clink_relcanonical%3E
# Also required for `sitemap.xml` generation at build time; which bots use to assist them crawling and indexing a website,
# the `mkdocs-material` 'Instant Navigation' feature utilizes the sitemap data to work.
site_url: https://alexander-rogalsky.gitbook.io/java-patterns/

# The main docs content lives here, any files will be copied over to the deployed version,
# unless the file or directory name is prefixed with a `.`
docs_dir: docs/

remote_branch: gh-pages

# Google analytics
# google_analytics: ['UA-7131053-20', 'auto']

# Project source specific data
repo_name: AlexRogalskiy/java-patterns
repo_url: https://github.com/AlexRogalskiy/java-patterns

# All docs `edit` button will go to this subpath of the `repo_url`:
# For versioned docs, this may be a little misleading for a user not viewing the `edge` docs which match the `master` branch.
edit_uri: edit/master/docs

# Copyright (shown at the footer)
copyright: Copyright &copy; 2021-2022 <a href="https://github.com/AlexRogalskiy/java-patterns"><em>Nullables.io</em></a><br/><span>This project is licensed under the MIT license.</span></p>
    <p>All rights reserved.</p>

# Other settings
use_directory_urls: true
strict: false # halt processing when a warning is raised

# Theme settings
theme:
  name: material
  language: en
  highlightjs: true
  custom_dir: docs/overrides
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logos/logo.svg
  favicon: assets/images/favicons/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.share
    - search.highlight
    - header.autohide
    - toc.integrate
    - toc.autohide
    - content.tabs.link
    - content.code.annotate
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'black'
      accent: 'grey'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Plugins settings
plugins:
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
  - mermaid2
  - search:
      lang:
        - en
        - ru
  - codeinclude
  - markdownextradata
  - i18n:
      default_language: en
      languages:
        en: English
        ru: Russian
  - git-revision-date-localized: # https://squidfunk.github.io/mkdocs-material/plugins/revision-date/
      fallback_to_build_date: true
      type: date
  - awesome-pages:
      filename: _config.yml # https://squidfunk.github.io/mkdocs-material/plugins/awesome-pages/
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - minify:
      minify_html: true
  - macros:
      modules:
        - docs.mkdocs_macros

# Extra settings
extra:
  homepage: https://alexander-rogalsky.gitbook.io/java-patterns/
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/AlexRogalskiy/java-patterns'
      name: Go to GitHub
    - icon: kofi
      link: https://ko-fi.com/alexrogalskiy
      name: Go to Kofi
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/alexanderr/styled-java-patterns
      name: Go to Docker Hub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexander-rogalskiy-985a4828/
      name: Go to LinkedIn
  version:
    provider: mike
    default: latest

# Extra css settings
extra_css:
  - assets/css/customizations.css
  - assets/css/asciinema-player.css
  - assets/css/extra.css

# Extra javascript settings
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://unpkg.com/mermaid@8.9.3/dist/mermaid.min.js
  - assets/js/asciinema-player.js
  - assets/js/chat.js
  - assets/js/sidecar-1.5.0.js

# Extensions settings
markdown_extensions:
  - toc:
      anchorlink: true
      permalink: true
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify
  - abbr: {}
  - attr_list: {}
  - def_list: {}
  - admonition: {} # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - footnotes: {}
  - tables: {}
  - meta: {}
  - md_in_html: {}
  - mkautodoc: {}
  - codehilite: # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
      linenums: true
      use_pygments: false
      guess_lang: false
  - pymdownx.highlight:
      linenums: true
      extend_pygments_lang:
        - name: yml
          lang: yaml
        - name: cf
          lang: cfg
        - name: conf
          lang: cfg
        - name: env
          lang: properties
        # Not helpful with Python Pygments lexer highlighting, but we might change to a JS highlighter in future
        # Ideally, this type of codefence might also have word-wrap enabled (CSS: {white-space: pre-wrap})
        - name: log
          lang: shell-session
        - name: fetchmailrc
          lang: txt
        - name: caddyfile
          lang: txt
  - pymdownx.escapeall: {}
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.extra: {}
  - pymdownx.snippets:
      base_path: docs/snippets
      check_paths: true
  - pymdownx.tilde: {}
  - pymdownx.magiclink:
      repo_url_shortener: true
      social_url_shortener: true
      user: AlexRogalskiy
      repo: java-patterns
  - pymdownx.caret: {}
  - pymdownx.keys: {}
  - pymdownx.smartsymbols: {}
  - pymdownx.progressbar: {}
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark: {}
  - pymdownx.critic: {}
  - pymdownx.inlinehilite: {} # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#inlinehilite
  - pymdownx.superfences: # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#superfences
     preserve_tabs: true
     custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed: {} # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#tabbed
  - pymdownx.details: {} # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#details
  - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - smarty: {} # https://python-markdown.github.io/extensions/smarty/
  - nl2br: {} # https://python-markdown.github.io/extensions/smarty/
  - mdx_truly_sane_lists: {} # https://github.com/radude/mdx_truly_sane_lists -> proper indentation of md list items
