apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    push: false
    tryImportMissing: false
    useDockerCLI: false
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: styled-java-patterns
      context: ./
      platforms: ["linux/amd64", "linux/arm64"]
      docker:
        dockerfile: ./distribution/docker-images/dev.Dockerfile
        pullParent: false
        noCache: false
        squash: false
deploy:
  statusCheckDeadlineSeconds: 300
  docker:
    useCompose: false
    images: [styled-java-patterns]
#   helm:
#     releases:
#       - name: java-patterns-charts
#         chartPath: charts
# #         setValueTemplates:
# #           image.repository: "{{.DOCKER_REGISTRY}}/gitcoinco/web"
# #           image.tag: "{{.DIGEST_HEX}}"
#         artifactOverrides:
#           deployment:
#             container:
#              image: styled-java-patterns
#         imageStrategy:
#           helm: {}
portForward:
  - resourceType: container
    resourceName: styled-java-patterns
    port: 8000
    address: 127.0.0.1
    localPort: 8000
