apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-patterns.name" . }}
  labels:
  {{- include "java-patterns.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
  {{- include "java-patterns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "java-patterns.selectorLabels" . | nindent 8 }}
      annotations:
        {{- range $key, $value := .Values.deployment.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
    {{- end }}
    spec:
      terminationGracePeriodSeconds: 30
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ template "java-patterns.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.container.image.repository }}:{{ .Values.deployment.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.container.image.pullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          {{- else if (or .Values.service.hostPort .Values.tls.hostPort) }}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort | default 8000 }}
              protocol: TCP
              {{- if .Values.service.hostPort }}
              hostPort: {{ .Values.service.hostPort }}
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: https
              containerPort: {{ .Values.tls.externalPort | default 8443 }}
              protocol: TCP
              {{- if .Values.tls.hostPort }}
              hostPort: {{ .Values.tls.hostPort }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            {{- if ne (.Values.deployment.container.port | int) (8000 | int) }}
            - name: PORT
              value: "{{ .Values.deployment.container.port }}"
            {{- end }}
            {{- if .Values.message }}
            - name: MESSAGE
              value: "{{ .Values.message }}"
            {{- end }}
            {{- if .Values.ingress.configured }}
            - name: HANDLER_PATH_PREFIX
              {{- if .Values.ingress.rewritePath }}
              value: ""
              {{- else }}
              value: "{{ .Values.ingress.pathPrefix }}"
            {{- end }}
            - name: RENDER_PATH_PREFIX
              value: "{{ .Values.ingress.pathPrefix }}"
            {{- end }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONTAINER_IMAGE
              value: "{{ .Values.deployment.container.image.repository }}:{{ .Values.deployment.container.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.deployment.resources }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: {{ .Values.tls.certPath | default "/data/cert" }}
              readOnly: true
          {{- end }}
          resources:
      {{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir: { }
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ template "java-patterns.tlsSecretName" . }}
  {{- end }}
  {{- end }}
