{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-patterns.name" . }}
  labels:
  {{- include "java-patterns.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    {{- if .Values.tls.enabled }}
    - port: {{ .Values.tls.httpPort | default 8000 }}
      targetPort: https
      protocol: TCP
      name: https
  {{- end }}
  selector:
  {{- include "java-patterns.selectorLabels" . | nindent 4 }}
  {{- end }}
