apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend
  namespace: secure
spec:
  dnsNames:
    - localhost
  secretName: backend-tls
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
