{{ if  (.Files.Glob "files/docker-entrypoint-initdb.d/*[sh|js|json]") }}
{{- $fullName := include "backend-java-patterns.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-init-scripts
  labels:
    {{- include "backend-java-patterns.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "files/docker-entrypoint-initdb.d/*[sh|js|json]").AsConfig . | indent 2 }}
{{ end }}
