{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-java-patterns.fullname" . }}
  labels:
    {{- include "backend-java-patterns.labels" . | nindent 4 }}
  {{- with .Values.secrets.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  BASE_URL: {{ default "" .Values.secrets.data.baseUrl | b64enc | quote }}
  {{- if .Values.secrets.data.baseToken }}
  BASE_TOKEN:  {{ .Values.secrets.data.baseToken | b64enc | quote }}
  {{- else }}
  BASE_TOKEN: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
