{{- if .Values.metrics.enabled }}
{{- $fullName := include "backend-java-patterns.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "backend-java-patterns.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- if .Values.metrics.labels }}
  {{- with .Values.metrics.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.metrics.service.annotations }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end }}
