{{- if .Values.service.enabled }}
{{- $fullName := include "backend-java-patterns.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "backend-java-patterns.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort | int64 }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.tls.enabled }}
    - port: {{ .Values.tls.httpPort | default 8000 | int64 }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "backend-java-patterns.selectorLabels" . | nindent 4 }}
{{- end }}
