theme: jekyll-theme-cayman

permalink: pretty

baseurl: https://github.com/AlexRogalskiy/java-patterns
title: Java Design Patterns
description:
  Explores different architectural concepts and design principles for Java
  applications

author: Alexander Rogalskiy

docs: https://github.com/AlexRogalskiy/java-patterns/wiki
blog: https://alexrogalskiy.github.io/

arrange:
  - articles
  - contributing
  - links
  - patterns
  - reporting
  - units
  - user-guide
