#!/bin/sh

FILE_NAME="$(dirname "$0")/_/husky.sh"

# Conditionally invoke so as to avoid running npm commands if this is a clean checkout (ie before installing npm modules)
if [ -f "$FILE_NAME" ]; then
  # shellcheck source=./_/husky.sh
  . "$FILE_NAME"

  command -v git-lfs >/dev/null 2>&1 || {
    echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"
    exit 2
  }
  git lfs post-checkout "$@"
fi
