name: automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: { }

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.repository == 'AlexRogalskiy/java-patterns'
    steps:
      - name: automerge
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"
        if: env.GITHUB_TOKEN != null
        uses: "pascalgn/automerge-action@v0.15.2"
