name: Latest articles and podcasts

on:
  workflow_dispatch:
  schedule:
    # Runs every day
    - cron: '0 1 * * *'

jobs:
  update-readme-with-posts:
    name: Update this repo's README with latest articles and podcasts on Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "REDDIT-POST-LIST"
          feed_list: "https://www.reddit.com/r/java/.rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "INFOWORLD-POST-LIST"
          feed_list: "https://www.infoworld.com/category/java/index.rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "LETSTALK-POST-LIST"
          feed_list: "http://letstalkaboutjava.blogspot.com/feeds/posts/default?alt=rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "RANDOMTHOUGHTS-POST-LIST"
          feed_list: "http://randomthoughtsonjavaprogramming.blogspot.com/feeds/posts/default?alt=rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "BETTERCODE-POST-LIST"
          feed_list: "https://betterjavacode.com/feed"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "INSIDE-POST-LIST"
          feed_list: "https://inside.java/feed.xml"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "JAVAPROG-POST-LIST"
          feed_list: "https://www.thejavaprogrammer.com/feed/"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "INFOQ-POST-LIST"
          feed_list: "https://feed.infoq.com/java"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "PLUMBR-POST-LIST"
          feed_list: "https://plumbr.io/blog/feed"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "TJ-POST-LIST"
          feed_list: "https://thorben-janssen.com/feed/"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "REDHAT-POST-LIST"
          feed_list: "https://developers.redhat.com/blog/tag/java/feed/"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "JAVACODEGEEKS-POST-LIST"
          feed_list: "https://www.javacodegeeks.com/feed"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "DEVCASES-POST-LIST"
          feed_list: "https://devcases.com/feed/"