name: Dead Link Checker

on:
  pull_request:

concurrency:
  group: dlc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  CheckDeadLinks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: sudo npm install -g markdown-link-check
      - run: |
          for file in $(find . -name "*.md"); do
            markdown-link-check -c .dlc.json -q "$file"
          done
