name: Download Link Check

on:
  deployment_status:

jobs:
  run:
    name: Initialize
    runs-on: ubuntu-latest
    if:
      github.event.deployment.ref != 'master' &&
      github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Download Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args:
            --verbose "${{ github.event.deployment.payload.web_url }}" --base
            "${{ github.event.deployment.payload.web_url }}" --include
            /download/

        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Check for Error Report
        if: hashFiles('./lychee/out.md') != ''
        run: |
          echo 'Errors were reported while checking download links.'
          exit 1
