name: Enforce PR labels for release drafter

on:
  pull_request:
    types: [ labeled, unlabeled, opened, edited, synchronize ]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.1
        with:
          REQUIRED_LABELS_ANY: "bug,enhancement,internal,no-changelog"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['bug','enhancement','internal','no-changelog'] for the PR"
