name: Greetings

on: [ pull_request, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |-
            Thank you for reporting the issue! If you haven't already [joined our github community](https://github.com/AlexRogalskiy/java-patterns/issues), then we invite you to do so.
            This is a great place to get help and ask questions from our AMAZING community.
            [![GitHub Community](https://github.githubassets.com/favicons/favicon.svg)](https://github.com/AlexRogalskiy/java-patterns/issues)
          pr-message: |-
            Thank you for submitting this PR! If you haven't already [joined our github community](https://github.com/AlexRogalskiy/java-patterns/issues), then we invite you to do so.
            We receive an overwhelming number of contributions. By joining our community, we'll be able to review your PR faster.
            [![GitHub Community](https://github.githubassets.com/favicons/favicon.svg)](https://github.com/AlexRogalskiy/java-patterns/issues)
