name: License Check

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  license-check:
    name: "License Check"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: Check License
        uses: apache/skywalking-eyes@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
