name: Merge master to develop

on:
  push:
    branches:
      - master

jobs:
  merge_master_to_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge master -> develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          head_to_merge: master
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
