name: Open Graph cards

on:
  workflow_dispatch:

jobs:
  docs-page-speed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Open Graph social cards
        uses: Jasmin2895/open-graph-image@v1.1
        with:
          bold-text: "Java Design patterns"
          plain-text: "https://alexander-rogalsky.gitbook.io/java-patterns"
          theme: "light"

      - name: Archive open graph image
        uses: actions/upload-artifact@v2
        with:
          name: open-graph-image
          path: images/generated/og-image.now.sh.png

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          skip_dirty_check: true
          commit_message: "docs: updates on open graph cards\n\n Added open graph cards"
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Bot
          commit_user_email: github-actions@nullables.io
          commit_author: GitHub Bot <github-actions@nullables.io>
