name: reviewdog

on: [ pull_request ]

jobs:
  remark-lint:
    name: runner / remark-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remark-lint
        uses: prologic/action-remark-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          fail_on_error: false
          reporter: github-pr-check # Change reporter. (Only `github-pr-check` is supported at the moment).
